### PR TITLE
Replace missing includes, fix table syntax, fix download macro

### LINKED ISSUE #8: replace missing includes
### Issue description

{% include_relative includes/mn-data-summary.md %}

### LINKED ISSUE #9: gdk download macro
### Issue description

CleanShot 2024-11-21 at 15 23 32@2x

### LINKED ISSUE #14: use asciidoc syntax for tables
### Issue description

https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/

### PR DESCRIPTION
**Pull request by AndreaLaGrotteria**

### CODE REVIEW

File: guides/src/main/java/io/micronaut/guides/core/GuidesConfigurationProperties.java [hunk 1]
```diff
@@ -38,14 +38,15 @@ public class GuidesConfigurationProperties implements GuidesConfiguration {
     private static final String LAUNCHER_URL = HOMEPAGE_URL + "/launch";
     private static final int DEFAULT_MIN_JDK = 17;
     private static final String API_URL = "https://docs.micronaut.io/latest/api";
-    private static final String DEFAULT_VERSION = "classpath:version.txt";
+    private static final String DEFAULT_VERSION = "0.0.0";
```
Comment (sdelamo) [inline guides/src/main/java/io/micronaut/guides/core/GuidesConfigurationProperties.java:41]: there was never a 0.0.0 version of Micronaut

**Review by sdelamo — APPROVED** [review]
